name: ecoadditions
main: xyz.garslity093.gerrysworld.ecoadditions.EcoAdditionsPlugin
version: 1.0.0
author: Gerry's world developers
api-version: 1.19
commands:
  ecoadditions:
    permission: ecoadditions.command