name: ecoadditions
main: xyz.garslity093.gerrysworld.ecoadditions.EcoAdditionsPlugin
version: 1.0.0
author: Gerry's world developers
depend:
  - Vault
  - NBTAPI
api-version: 1.13
commands:
  ecoadditions:
    permission: ecoadditions.command